services:
  grafana-alloy:
    image: grafana/alloy:latest
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - elk

  pm-api:
    build:
      context: ../server
      dockerfile: PM.API/Dockerfile
    env_file:
      - .env
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5130
    ports:
      - "5130:5130"
    depends_on:
      grafana-alloy:
        condition: service_started
    networks:
      - elk

networks:
  elk:

volumes:
  grafana-storage: