services:
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: pmdb
    ports:
      - "5432:5432"
    networks:
      - elk

  cassandra-db:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=PMCluster
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - elk

  grafana-alloy:
    image: grafana/alloy:latest
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy
    command: run --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    env_file:
      - .env
    depends_on:
      - postgres-db
      - cassandra-db
    networks:
      - elk

  pm-api:
    build:
      context: ../server
      dockerfile: PM.API/Dockerfile
    env_file:
      - .env
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5130
      - ConnectionStrings__DefaultConnection=Server=postgres-db;Port=5432;Database=pmdb;User Id=postgres;Password=postgrespassword;
      - Cassandra__ContactPoints__0=cassandra-db
    ports:
      - "5130:5130"
    depends_on:
      postgres-db:
        condition: service_started
      cassandra-db:
        condition: service_started
      grafana-alloy:
        condition: service_started
    networks:
      - elk

networks:
  elk:

volumes:
  grafana-storage: