export async function getMentors() {
  return [
    {
      id: "1",
      name: "Ivan Petrov",
      subject: "Math",
      rating: 4.9,
      experience: "10+ years",
      students: 245,
      price: "$25/hr",
    },
    {
      id: "2",
      name: "Maria Dimitrova",
      subject: "English",
      rating: 4.8,
      experience: "8 years",
      students: 189,
      price: "$20/hr",
    },
    {
      id: "3",
      name: "Alex Johnson",
      subject: "Physics",
      rating: 4.7,
      experience: "7 years",
      students: 156,
      price: "$28/hr",
    },
    {
      id: "4",
      name: "Sofia Rodriguez",
      subject: "Chemistry",
      rating: 4.9,
      experience: "9 years",
      students: 212,
      price: "$26/hr",
    },
    {
      id: "5",
      name: "Michael Chen",
      subject: "Programming",
      rating: 4.8,
      experience: "6 years",
      students: 324,
      price: "$35/hr",
    },
    {
      id: "6",
      name: "Emma Watson",
      subject: "History",
      rating: 4.6,
      experience: "5 years",
      students: 98,
      price: "$18/hr",
    },
    {
      id: "7",
      name: "David Kumar",
      subject: "Math",
      rating: 4.8,
      experience: "12 years",
      students: 278,
      price: "$30/hr",
    },
    {
      id: "8",
      name: "Lisa Anderson",
      subject: "Biology",
      rating: 4.7,
      experience: "8 years",
      students: 167,
      price: "$24/hr",
    },
    {
      id: "9",
      name: "James Wilson",
      subject: "English",
      rating: 4.9,
      experience: "11 years",
      students: 301,
      price: "$27/hr",
    },
    {
      id: "10",
      name: "Nina Patel",
      subject: "Chemistry",
      rating: 4.7,
      experience: "6 years",
      students: 134,
      price: "$22/hr",
    },
  ];
}
